## Importing the Libraries

In [1]:
%pip install nltk

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
from torch.utils.data import Dataset,DataLoader
from nltk.tokenize import word_tokenize
import nltk

In [3]:
document = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The cours"e follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""


## Tokenizing the Text

In [4]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [6]:
tokens = word_tokenize(document.lower())

In [7]:
word_tokenize(document.lower())

['about',
 'the',
 'program',
 'what',
 'is',
 'the',
 'course',
 'fee',
 'for',
 'data',
 'science',
 'mentorship',
 'program',
 '(',
 'dsmp',
 '2023',
 ')',
 'the',
 'cours',
 "''",
 'e',
 'follows',
 'a',
 'monthly',
 'subscription',
 'model',
 'where',
 'you',
 'have',
 'to',
 'make',
 'monthly',
 'payments',
 'of',
 'rs',
 '799/month',
 '.',
 'what',
 'is',
 'the',
 'total',
 'duration',
 'of',
 'the',
 'course',
 '?',
 'the',
 'total',
 'duration',
 'of',
 'the',
 'course',
 'is',
 '7',
 'months',
 '.',
 'so',
 'the',
 'total',
 'course',
 'fee',
 'becomes',
 '799',
 '*',
 '7',
 '=',
 'rs',
 '5600',
 '(',
 'approx',
 '.',
 ')',
 'what',
 'is',
 'the',
 'syllabus',
 'of',
 'the',
 'mentorship',
 'program',
 '?',
 'we',
 'will',
 'be',
 'covering',
 'the',
 'following',
 'modules',
 ':',
 'python',
 'fundamentals',
 'python',
 'libraries',
 'for',
 'data',
 'science',
 'data',
 'analysis',
 'sql',
 'for',
 'data',
 'science',
 'maths',
 'for',
 'machine',
 'learning',
 'ml',
 'algo

In [10]:
vocab = {'<UNK>':0}

for token in Counter(tokens).keys():
  vocab[token] = len(vocab)

In [11]:
vocab

{'<UNK>': 0,
 'about': 1,
 'the': 2,
 'program': 3,
 'what': 4,
 'is': 5,
 'course': 6,
 'fee': 7,
 'for': 8,
 'data': 9,
 'science': 10,
 'mentorship': 11,
 '(': 12,
 'dsmp': 13,
 '2023': 14,
 ')': 15,
 'cours': 16,
 "''": 17,
 'e': 18,
 'follows': 19,
 'a': 20,
 'monthly': 21,
 'subscription': 22,
 'model': 23,
 'where': 24,
 'you': 25,
 'have': 26,
 'to': 27,
 'make': 28,
 'payments': 29,
 'of': 30,
 'rs': 31,
 '799/month': 32,
 '.': 33,
 'total': 34,
 'duration': 35,
 '?': 36,
 '7': 37,
 'months': 38,
 'so': 39,
 'becomes': 40,
 '799': 41,
 '*': 42,
 '=': 43,
 '5600': 44,
 'approx': 45,
 'syllabus': 46,
 'we': 47,
 'will': 48,
 'be': 49,
 'covering': 50,
 'following': 51,
 'modules': 52,
 ':': 53,
 'python': 54,
 'fundamentals': 55,
 'libraries': 56,
 'analysis': 57,
 'sql': 58,
 'maths': 59,
 'machine': 60,
 'learning': 61,
 'ml': 62,
 'algorithms': 63,
 'practical': 64,
 'mlops': 65,
 'case': 66,
 'studies': 67,
 'can': 68,
 'check': 69,
 'detailed': 70,
 'here': 71,
 '-': 72,
 '

In [12]:
len(vocab)

292

## Extracting Sentences from Document

In [16]:
input_sentences = nltk.sent_tokenize(document)

In [17]:
input_sentences

['About the Program\nWhat is the course fee for  Data Science Mentorship Program (DSMP 2023)\nThe cours"e follows a monthly subscription model where you have to make monthly payments of Rs 799/month.',
 'What is the total duration of the course?',
 'The total duration of the course is 7 months.',
 'So the total course fee becomes 799*7 = Rs 5600(approx.)',
 'What is the syllabus of the mentorship program?',
 'We will be covering the following modules:\nPython Fundamentals\nPython libraries for Data Science\nData Analysis\nSQL for Data Science\nMaths for Machine Learning\nML Algorithms\nPractical ML\nMLOPs\nCase studies\nYou can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390\nWill Deep Learning and NLP be a part of this program?',
 'No, NLP and Deep Learning both are not a part of this program’s curriculum.',
 'What if I miss a live session?',
 'Will I get a recording of the session?',
 'Yes all ou

In [19]:
def text_to_indices(sentence,vocab):
  numerical_sentences = []
  for token in sentence:
    if token in vocab:
      numerical_sentences.append(vocab[token])
    else:
      numerical_sentences.append(vocab['<UNK>'])
  return numerical_sentences

In [20]:
input_numerical_sentences = []
for sentence in input_sentences:
  input_numerical_sentences.append(text_to_indices(word_tokenize(sentence.lower()),vocab))

In [21]:
input_numerical_sentences

[[1,
  2,
  3,
  4,
  5,
  2,
  6,
  7,
  8,
  9,
  10,
  11,
  3,
  12,
  13,
  14,
  15,
  2,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  21,
  29,
  30,
  31,
  32,
  33],
 [4, 5, 2, 34, 35, 30, 2, 6, 36],
 [2, 34, 35, 30, 2, 6, 5, 37, 38, 33],
 [39, 2, 34, 6, 7, 40, 41, 42, 37, 43, 31, 44, 12, 45, 33, 15],
 [4, 5, 2, 46, 30, 2, 11, 3, 36],
 [47,
  48,
  49,
  50,
  2,
  51,
  52,
  53,
  54,
  55,
  54,
  56,
  8,
  9,
  10,
  9,
  57,
  58,
  8,
  9,
  10,
  59,
  8,
  60,
  61,
  62,
  63,
  64,
  62,
  65,
  66,
  67,
  25,
  68,
  69,
  2,
  70,
  46,
  71,
  72,
  73,
  53,
  74,
  48,
  75,
  61,
  76,
  77,
  49,
  20,
  78,
  30,
  79,
  3,
  36],
 [80, 81, 77, 76, 75, 61, 82, 83, 84, 20, 78, 30, 79, 3, 85, 86, 87, 33],
 [4, 88, 89, 90, 20, 91, 92, 36],
 [48, 89, 93, 20, 94, 30, 2, 92, 36],
 [95,
  96,
  97,
  98,
  83,
  99,
  81,
  39,
  100,
  88,
  25,
  90,
  20,
  92,
  25,
  68,
  101,
  102,
  76,
  103,
  2,
  94,
  33],
 [24, 68

In [22]:
len(input_numerical_sentences)

65

In [24]:
training_sequence = []
for sentence in input_numerical_sentences:
  for i in range(1,len(sentence)):
    training_sequence.append(sentence[:i+1])

In [27]:
len(training_sequence)

958

In [28]:
training_sequence[:5]

[[1, 2], [1, 2, 3], [1, 2, 3, 4], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 2]]

In [30]:
"""We need to pre-Pad the Token, Because the LSTM accepts the Same size tokens as input"""
"""1. We find the Longest Sequence"""
len_list= []
for sentence in training_sequence:
  len_list.append(len(sentence))
max(len_list)

55

In [31]:
padded_training_sequence = []
for sequence in training_sequence:
  padded_training_sequence.append([0]*(max(len_list)-len(sequence)) + sequence)

In [32]:
padded_training_sequence

[[0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  

In [33]:
print(f"Length of the Sentence is {len(padded_training_sequence[0])}")

Length of the Sentence is 55


In [35]:
padded_training_sequence = torch.tensor(padded_training_sequence,dtype = torch.long)

In [36]:
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   2,   3,   4],
        ...,
        [  0,   0,   0,  ..., 288, 179, 289],
        [  0,   0,   0,  ..., 179, 289, 290],
        [  0,   0,   0,  ..., 289, 290, 291]])

In [37]:
X = padded_training_sequence[:,:-1]
y = padded_training_sequence[:,-1]

In [38]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        ...,
        [  0,   0,   0,  ..., 287, 288, 179],
        [  0,   0,   0,  ..., 288, 179, 289],
        [  0,   0,   0,  ..., 179, 289, 290]])

In [39]:
y

tensor([  2,   3,   4,   5,   2,   6,   7,   8,   9,  10,  11,   3,  12,  13,
         14,  15,   2,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  21,  29,  30,  31,  32,  33,   5,   2,  34,  35,  30,   2,
          6,  36,  34,  35,  30,   2,   6,   5,  37,  38,  33,   2,  34,   6,
          7,  40,  41,  42,  37,  43,  31,  44,  12,  45,  33,  15,   5,   2,
         46,  30,   2,  11,   3,  36,  48,  49,  50,   2,  51,  52,  53,  54,
         55,  54,  56,   8,   9,  10,   9,  57,  58,   8,   9,  10,  59,   8,
         60,  61,  62,  63,  64,  62,  65,  66,  67,  25,  68,  69,   2,  70,
         46,  71,  72,  73,  53,  74,  48,  75,  61,  76,  77,  49,  20,  78,
         30,  79,   3,  36,  81,  77,  76,  75,  61,  82,  83,  84,  20,  78,
         30,  79,   3,  85,  86,  87,  33,  88,  89,  90,  20,  91,  92,  36,
         89,  93,  20,  94,  30,   2,  92,  36,  96,  97,  98,  83,  99,  81,
         39, 100,  88,  25,  90,  20,  92,  25,  68, 101, 102,  

## Creating the Dataset and DataLoader

In [43]:
class CustomDataset(Dataset):
  def __init__(self,X,y):
    self.X = X
    self.y = y

  def __len__(self):
    return len(self.X)

  def __getitem__(self,idx):
    return self.X[idx],self.y[idx]

In [44]:
dataset = CustomDataset(X,y)

In [45]:
len(dataset)

958

In [46]:
dataloader = DataLoader(dataset,batch_size=32,shuffle=True)

In [47]:
for input,output in dataloader:
  print(input,output)

tensor([[  0,   0,   0,  ..., 186,  30,  21],
        [  0,   0,   0,  ...,  85, 159,  26],
        [  0,   0,   0,  ...,  27, 103,   2],
        ...,
        [  0,   0,   0,  ..., 138,  79,   6],
        [  0,   0,   0,  ...,  83, 119, 259],
        [  0,   0,   0,  ...,  56,   8,   9]]) tensor([ 22,  27, 134, 151,   3,  89, 223, 182,   9, 169,  47,  92,  25, 268,
        152, 146, 104, 238,  33, 144, 156,  86,  83,  88,  53,  20,   2, 259,
        108,  88,  53,  10])
tensor([[  0,   0,   0,  ..., 139,  84, 149],
        [  0,   0,   0,  ..., 103,   2, 134],
        [  0,   0,   0,  ...,   0,  48,  89],
        ...,
        [  0,   0,   0,  ..., 111, 112, 111],
        [  0,   0,   0,  ...,  76,  89, 139],
        [  0,   0,   0,  ..., 131, 132, 133]]) tensor([ 27,  98,  93,   2, 199,   5, 139,  27, 166,  81,  97,  27,   2,   2,
          2,  24, 241,  30,  38, 276,  48,  33,   5, 143,  33, 179,   2, 246,
         45, 113,  84, 134])
tensor([[  0,   0,   0,  ...,  96, 168, 135],
    

In [48]:
vocab_size = len(vocab)

## Implementing the LSTM Architecture

In [90]:
class LSTMModel(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size,100)
    self.lstm = nn.LSTM(100,150,batch_first = True)
    self.fc = nn.Linear(150,vocab_size)

  def forward(self,X):
    embedded = self.embedding(X)
    intermediate_hidden_state,(final_hidden_state,final_cell_state) = self.lstm(embedded)
    output = self.fc(final_hidden_state.squeeze(0))
    return output

In [91]:
model = LSTMModel(vocab_size)

In [92]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [93]:
model.to(device)

LSTMModel(
  (embedding): Embedding(292, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=292, bias=True)
)

In [94]:
epochs = 50
learning_rate = 0.001

In [95]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(),lr = learning_rate)

In [96]:
"""Training Loop"""
for epoch in range(epochs):
  total_loss = 0
  for batch_x,batch_y in dataloader:
    batch_x = batch_x.to(device)
    batch_y = batch_y.to(device)


    optimizer.zero_grad()
    output = model(batch_x)
    loss = criterion(output,batch_y)

    loss.backward()
    optimizer.step()
    total_loss += loss.item()
  print(f"Epoch: {epoch+1} Loss: {total_loss/len(dataloader)}")

Epoch: 1 Loss: 5.511866601308187
Epoch: 2 Loss: 4.9049087842305505
Epoch: 3 Loss: 4.539170535405477
Epoch: 4 Loss: 4.155458593368531
Epoch: 5 Loss: 3.7616878588994345
Epoch: 6 Loss: 3.3786790053049724
Epoch: 7 Loss: 3.033137289683024
Epoch: 8 Loss: 2.6936113516489666
Epoch: 9 Loss: 2.3876973827679953
Epoch: 10 Loss: 2.1027753194173178
Epoch: 11 Loss: 1.8483168721199035
Epoch: 12 Loss: 1.6332898259162902
Epoch: 13 Loss: 1.4248412370681762
Epoch: 14 Loss: 1.2546620786190033
Epoch: 15 Loss: 1.1073538104693095
Epoch: 16 Loss: 0.9742615103721619
Epoch: 17 Loss: 0.8604063153266907
Epoch: 18 Loss: 0.7659920553366343
Epoch: 19 Loss: 0.6823408166567485
Epoch: 20 Loss: 0.6094511608282726
Epoch: 21 Loss: 0.5526287476221721
Epoch: 22 Loss: 0.5020258446534475
Epoch: 23 Loss: 0.45534876386324563
Epoch: 24 Loss: 0.4181605925162633
Epoch: 25 Loss: 0.3825601994991302
Epoch: 26 Loss: 0.3563170596957207
Epoch: 27 Loss: 0.33175629178682964
Epoch: 28 Loss: 0.3110930581887563
Epoch: 29 Loss: 0.2916310687859

## Prediction

In [107]:
def prediction(model,vocab,text):

  # tokenize
  tokenized_text = word_tokenize(text.lower())


  # text -> numerical_indices
  numerical_text = text_to_indices(word_tokenize(text.lower()),vocab)

  # padding
  padded_text = [0] * (55 - len(numerical_text)) + numerical_text
  input_tensor = torch.tensor(padded_text,dtype = torch.long).unsqueeze(0)

  # send to model
  output = model(input_tensor)

  # predicted model

  value,index = torch.max(output,dim = 1)
  predicted_word = list(vocab.keys())[list(vocab.values()).index(index.item())]

  return text + " " + list(vocab.keys())[index]

In [113]:
import time

num_tokens = 25
input_text = "What is "

for i in range(num_tokens):
  output_text = prediction(model, vocab, input_text)
  print(output_text)
  input_text = output_text
  time.sleep(0.5)


What is  the
What is  the refund
What is  the refund policy
What is  the refund policy ?
What is  the refund policy ? ?
What is  the refund policy ? ? ?
What is  the refund policy ? ? ? usp=sharing
What is  the refund policy ? ? ? usp=sharing .
What is  the refund policy ? ? ? usp=sharing . .
What is  the refund policy ? ? ? usp=sharing . . )
What is  the refund policy ? ? ? usp=sharing . . ) the
What is  the refund policy ? ? ? usp=sharing . . ) the sessions
What is  the refund policy ? ? ? usp=sharing . . ) the sessions sessions
What is  the refund policy ? ? ? usp=sharing . . ) the sessions sessions with
What is  the refund policy ? ? ? usp=sharing . . ) the sessions sessions with industry
What is  the refund policy ? ? ? usp=sharing . . ) the sessions sessions with industry mentors
What is  the refund policy ? ? ? usp=sharing . . ) the sessions sessions with industry mentors discussion
What is  the refund policy ? ? ? usp=sharing . . ) the sessions sessions with industry mentors di

## Dry Run

In [62]:
x = nn.Embedding(292,100)
y = nn.LSTM(100,150,batch_first=True)
z = nn.Linear(150,292)

In [63]:
a = dataset[0][0].unsqueeze(0)

In [64]:
a.shape

torch.Size([1, 54])

In [65]:
b = x(a)

In [66]:
y(b)

(tensor([[[-0.0761,  0.1209,  0.1882,  ...,  0.0042,  0.1514,  0.0341],
          [-0.1082,  0.1675,  0.2740,  ...,  0.0339,  0.2391,  0.0372],
          [-0.1217,  0.1898,  0.3146,  ...,  0.0586,  0.2858,  0.0331],
          ...,
          [-0.1439,  0.2216,  0.3557,  ...,  0.0957,  0.3451,  0.0144],
          [-0.1439,  0.2216,  0.3557,  ...,  0.0957,  0.3451,  0.0144],
          [-0.0104,  0.2828,  0.0911,  ...,  0.1038,  0.1586, -0.0603]]],
        grad_fn=<TransposeBackward0>),
 (tensor([[[-0.0104,  0.2828,  0.0911,  0.0020, -0.2677,  0.0510,  0.1218,
             0.2168,  0.0725, -0.0441,  0.0442, -0.2368,  0.0912,  0.1404,
            -0.1027, -0.0084,  0.0194, -0.0630,  0.2623,  0.1471,  0.1260,
            -0.0023, -0.0752,  0.0320, -0.0619,  0.1263, -0.0088,  0.0621,
            -0.3473,  0.1059,  0.1049,  0.1319, -0.2062,  0.0755, -0.0505,
            -0.0120, -0.1344, -0.0107, -0.1630,  0.0311, -0.0288, -0.1262,
             0.1008, -0.0373,  0.1508,  0.0448, -0.0196, -0.09

In [67]:
c,d = y(b)

In [68]:
c.shape

torch.Size([1, 54, 150])

In [69]:
e,f = d ## Final Cell States

In [70]:
e.shape

torch.Size([1, 1, 150])

In [71]:
f.shape

torch.Size([1, 1, 150])

In [73]:
z(f.squeeze(0)) ## final Number of each Logit, Also Known as Probability of each word

tensor([[ 0.1872,  0.0067, -0.0782, -0.1584,  0.1124, -0.2192, -0.0207, -0.1665,
          0.0463,  0.2157, -0.1839, -0.2076, -0.1831, -0.0886, -0.3846,  0.2699,
          0.0742, -0.1892,  0.2645,  0.0878,  0.0698,  0.3183,  0.1283,  0.0181,
          0.0922,  0.0132, -0.1272,  0.0445, -0.3025, -0.1934,  0.0746,  0.2635,
         -0.0243, -0.1139,  0.2071,  0.0677,  0.0849, -0.1809, -0.0271,  0.1982,
          0.0205, -0.2596, -0.0545, -0.0276,  0.0119, -0.1874, -0.0508, -0.2055,
         -0.2208, -0.0398,  0.1191,  0.0191, -0.1287, -0.0826,  0.3035,  0.1142,
         -0.4542,  0.2057,  0.0202, -0.0379,  0.0205,  0.1461, -0.0917, -0.0631,
          0.1729,  0.0308,  0.0652,  0.1408,  0.5913, -0.1042,  0.0755, -0.3017,
          0.1467,  0.0148, -0.1302, -0.1564,  0.1947,  0.0667,  0.1418,  0.3083,
          0.2590,  0.2300, -0.2040,  0.1192,  0.1520,  0.3829,  0.1663, -0.1921,
         -0.0555, -0.0467,  0.1586,  0.1568,  0.1245, -0.0470, -0.2740,  0.0830,
         -0.2204, -0.0376, -