In [8]:
import torch
import torch.nn as nn

"""We are inheriting the properties fom the NN module"""
class Model(nn.Module):
  def __init__(self,num_features):

    """ Calling the Parent Class from the Child Class"""
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [17]:
import torch
import torch.nn as nn

"""We are inheriting the properties fom the NN module"""
class Model2(nn.Module):
  def __init__(self,num_features):

    """ Calling the Parent Class from the Child Class"""
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3), ## 3 - Output of the Hidden Layer
        nn.ReLU(),
        nn.Linear(3,1), ## 3 - Iput of the final Layer and 1 - Output of the Last layer
        nn.Sigmoid()
    )

  def forward(self,features):
    out = self.network(features)
    return out

In [18]:
features = torch.rand(10,5)

"""Creating a instance of Model"""
model = Model2(features.shape[1])

model(features) ## Automatically the Forward Function is trigerred

tensor([[0.6143],
        [0.6125],
        [0.6143],
        [0.6143],
        [0.6143],
        [0.6143],
        [0.6072],
        [0.6120],
        [0.6143],
        [0.6114]], grad_fn=<SigmoidBackward0>)

In [22]:
print(model.network[0].weight)
print(model.network[2].weight)

Parameter containing:
tensor([[-0.2190,  0.2621,  0.2551, -0.2064, -0.2363],
        [-0.3522, -0.1202, -0.3167, -0.1893, -0.1422],
        [-0.0367,  0.0261, -0.2606, -0.3293, -0.2407]], requires_grad=True)
Parameter containing:
tensor([[-0.3938, -0.3469, -0.4966]], requires_grad=True)


In [13]:
model.linear2.weight

Parameter containing:
tensor([[-0.5381, -0.5272, -0.3588]], requires_grad=True)

In [14]:
%pip install torchinfo

In [15]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00