In [117]:
import torch
print(torch.__version__)

2.11.0+cu128


In [118]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU Not available!")

GPU is available
Using GPU: Tesla T4


## Creating a Tensor

In [119]:
""" Using the empty Function"""
a = torch.empty(2,3)

In [120]:
type(a)

torch.Tensor

In [121]:
""" Using the zero Function"""
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [122]:
""" Using the ones Function"""
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [123]:
""" Using the rand Function"""
torch.rand(2,3)

tensor([[0.3397, 0.2102, 0.9003],
        [0.9300, 0.2240, 0.2525]])

In [124]:
""" Using the seed Function"""
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [125]:
""" Using the manual seed Function"""
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [126]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [127]:
""" Using the tensor Function"""
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [128]:
""" Using the arange Function"""
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [129]:
""" Using the linspace Function"""
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [130]:
""" Using the eye Function"""
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [131]:
""" Using the full Function"""
torch.full((2,2),5)

tensor([[5, 5],
        [5, 5]])

## Tensor shapes

In [132]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [133]:
torch.empty_like(x)

tensor([[137252301176192, 137252301176192,               0],
        [              0,               0,               0]])

In [134]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [135]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [136]:
torch.rand_like(x,dtype = torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Torch Data Types

In [137]:
""" find data Type"""
x.dtype

torch.int64

In [138]:
""" Assign Data Type """
torch.tensor([1,2,3],dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [139]:
""" Changing an exisiting data Type """
x.to(dtype = torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical Operations

In [140]:
x = torch.rand(2,2)

In [141]:
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [142]:
""" Addition """
x + 2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [143]:
""" Sbubtraction """
x - 2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [144]:
""" Multiplication """
x * 3

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [145]:
""" Divison """
x / 3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [146]:
""" int Divison """
(x * 100)// 3

tensor([[23., 26.],
        [13., 30.]])

In [147]:
""" Power """
x ** 2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

## Element wise Operations

In [148]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [149]:
b

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])

In [150]:
a + b # Element-wise addition

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [151]:
a - b # Element-wise subtraction

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [152]:
a * b # Element-wise multiplication

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [153]:
a / b # Element-wise division

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [154]:
a // b # Element-wise integer division

tensor([[1., 0., 0.],
        [0., 0., 1.]])

In [155]:
a ** b # Element-wise power

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [156]:
c = torch.tensor([1,-2,3,-4])


In [157]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [158]:
# negative
torch.negative(c)

tensor([-1,  2, -3,  4])

In [159]:
d = torch.Tensor([1.9,2.3,3.7,4.4])

In [160]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [161]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [162]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [163]:
# clamp
torch.clamp(d,min = 2,max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## Reduction Operations

In [164]:
e = torch.randint(size = (2,3), low = 0, high = 10,dtype = torch.float32)

In [165]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e,dim =0)
# sum along rows
torch.sum(e,dim = 1)

tensor([15.,  9.])

In [166]:
# mean
torch.mean(e)
# mean along columns
torch.mean(e,dim =0)
# mean along rows
torch.mean(e,dim = 1)

tensor([5., 3.])

In [167]:
# median
torch.mean(e)
# median along columns
torch.mean(e,dim =0)
# median along rows
torch.mean(e,dim = 1)

tensor([5., 3.])

In [168]:
#max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [169]:
#product
torch.prod(e)

tensor(0.)

In [170]:
# standard Deviation
torch.std(x)

tensor(0.2063)

In [171]:
# variance
torch.var(x)

tensor(0.0425)

In [172]:
# argmax
torch.argmax(e)
"""Find the position of largest item """

'Find the position of largest item '

In [173]:
# argmin
torch.argmin(e)
"""Find the position of smallest item """

'Find the position of smallest item '

### Matrix Operations

In [174]:
f = torch.randint(size = (2,3), low = 0, high = 10)
g = torch.randint(size = (2,3), low = 0, high = 10)

In [175]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

In [176]:
torch.dot(vector1,vector2)

tensor(11)

In [177]:
torch.transpose(f,0,1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [178]:

h = torch.randint(size = (3,3), low = 0, high = 10,dtype = torch.float32)

In [179]:
torch.det(h)

tensor(-110.)

In [180]:
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

## Comparision Operations

In [181]:
i = torch.randint(size = (2,3), low = 0, high = 10)
j = torch.randint(size = (2,3), low = 0, high = 10)

In [182]:
#greater than
#less tham
# equal to
#not equal tro
# greater than equal to
# Lesss than equal to

In [183]:
print(f"i: {i}")
print(f"j: {j}")

print("Greater than (i > j):")
print(i > j)

print("Less than (i < j):")
print(i < j)

print("Equal to (i == j):")
print(i == j)

print("Not equal to (i != j):")
print(i != j)

print("Greater than or equal to (i >= j):")
print(i >= j)

print("Less than or equal to (i <= j):")
print(i <= j)

i: tensor([[7, 8, 3],
        [6, 1, 5]])
j: tensor([[5, 0, 4],
        [3, 8, 8]])
Greater than (i > j):
tensor([[ True,  True, False],
        [ True, False, False]])
Less than (i < j):
tensor([[False, False,  True],
        [False,  True,  True]])
Equal to (i == j):
tensor([[False, False, False],
        [False, False, False]])
Not equal to (i != j):
tensor([[True, True, True],
        [True, True, True]])
Greater than or equal to (i >= j):
tensor([[ True,  True, False],
        [ True, False, False]])
Less than or equal to (i <= j):
tensor([[False, False,  True],
        [False,  True,  True]])


## Special Function

In [184]:
k = torch.randint(size = (32,3), low = 0, high = 10,dtype = torch.float32)

In [185]:
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863],
        [  -inf, 2.0794, 1.3863],
        [1.9459, 0.6931, 1.0986],
        [2.0794, 1.6094, 1.7918],
        [0.6931, 2.1972, 1.6094],
        [  -inf, 1.3863, 0.6931],
        [1.9459, 0.0000, 0.0000],
        [1.6094, 1.3863, 1.3863],
        [0.0000, 0.0000, 0.6931],
        [1.3863, 1.9459, 0.6931],
        [1.6094, 1.7918, 0.0000],
        [1.3863, 1.6094, 1.7918],
        [2.1972, 0.6931, 1.0986],
        [0.0000,   -inf, 0.6931],
        [0.0000, 0.6931, 1.9459],
        [2.1972, 0.6931, 1.3863],
        [1.7918, 1.7918, 2.0794],
        [1.3863, 2.1972,   -inf],
        [1.9459, 2.1972, 0.6931],
        [1.9459,   -inf, 0.6931],
        [1.3863, 1.3863, 1.7918],
        [0.6931, 0.0000,   -inf],
        [1.6094, 0.0000,   -inf],
        [  -inf, 0.6931, 0.6931],
        [1.0986, 1.9459, 0.0000],
        [1.6094,   -inf, 0.6931],
        [1.0986, 1.9459,   -inf],
        [0.6931, 1.6094, 0.6931],
        [2.079

In [186]:
torch.exp(k)

tensor([[2.0086e+01, 2.0086e+01, 1.4841e+02],
        [1.0000e+00, 4.0343e+02, 5.4598e+01],
        [1.0000e+00, 2.9810e+03, 5.4598e+01],
        [1.0966e+03, 7.3891e+00, 2.0086e+01],
        [2.9810e+03, 1.4841e+02, 4.0343e+02],
        [7.3891e+00, 8.1031e+03, 1.4841e+02],
        [1.0000e+00, 5.4598e+01, 7.3891e+00],
        [1.0966e+03, 2.7183e+00, 2.7183e+00],
        [1.4841e+02, 5.4598e+01, 5.4598e+01],
        [2.7183e+00, 2.7183e+00, 7.3891e+00],
        [5.4598e+01, 1.0966e+03, 7.3891e+00],
        [1.4841e+02, 4.0343e+02, 2.7183e+00],
        [5.4598e+01, 1.4841e+02, 4.0343e+02],
        [8.1031e+03, 7.3891e+00, 2.0086e+01],
        [2.7183e+00, 1.0000e+00, 7.3891e+00],
        [2.7183e+00, 7.3891e+00, 1.0966e+03],
        [8.1031e+03, 7.3891e+00, 5.4598e+01],
        [4.0343e+02, 4.0343e+02, 2.9810e+03],
        [5.4598e+01, 8.1031e+03, 1.0000e+00],
        [1.0966e+03, 8.1031e+03, 7.3891e+00],
        [1.0966e+03, 1.0000e+00, 7.3891e+00],
        [5.4598e+01, 5.4598e+01, 4

In [187]:
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000],
        [0.0000, 2.8284, 2.0000],
        [2.6458, 1.4142, 1.7321],
        [2.8284, 2.2361, 2.4495],
        [1.4142, 3.0000, 2.2361],
        [0.0000, 2.0000, 1.4142],
        [2.6458, 1.0000, 1.0000],
        [2.2361, 2.0000, 2.0000],
        [1.0000, 1.0000, 1.4142],
        [2.0000, 2.6458, 1.4142],
        [2.2361, 2.4495, 1.0000],
        [2.0000, 2.2361, 2.4495],
        [3.0000, 1.4142, 1.7321],
        [1.0000, 0.0000, 1.4142],
        [1.0000, 1.4142, 2.6458],
        [3.0000, 1.4142, 2.0000],
        [2.4495, 2.4495, 2.8284],
        [2.0000, 3.0000, 0.0000],
        [2.6458, 3.0000, 1.4142],
        [2.6458, 0.0000, 1.4142],
        [2.0000, 2.0000, 2.4495],
        [1.4142, 1.0000, 0.0000],
        [2.2361, 1.0000, 0.0000],
        [0.0000, 1.4142, 1.4142],
        [1.7321, 2.6458, 1.0000],
        [2.2361, 0.0000, 1.4142],
        [1.7321, 2.6458, 0.0000],
        [1.4142, 2.2361, 1.4142],
        [2.828

In [188]:
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820],
        [0.5000, 0.9997, 0.9820],
        [0.9991, 0.8808, 0.9526],
        [0.9997, 0.9933, 0.9975],
        [0.8808, 0.9999, 0.9933],
        [0.5000, 0.9820, 0.8808],
        [0.9991, 0.7311, 0.7311],
        [0.9933, 0.9820, 0.9820],
        [0.7311, 0.7311, 0.8808],
        [0.9820, 0.9991, 0.8808],
        [0.9933, 0.9975, 0.7311],
        [0.9820, 0.9933, 0.9975],
        [0.9999, 0.8808, 0.9526],
        [0.7311, 0.5000, 0.8808],
        [0.7311, 0.8808, 0.9991],
        [0.9999, 0.8808, 0.9820],
        [0.9975, 0.9975, 0.9997],
        [0.9820, 0.9999, 0.5000],
        [0.9991, 0.9999, 0.8808],
        [0.9991, 0.5000, 0.8808],
        [0.9820, 0.9820, 0.9975],
        [0.8808, 0.7311, 0.5000],
        [0.9933, 0.7311, 0.5000],
        [0.5000, 0.8808, 0.8808],
        [0.9526, 0.9991, 0.7311],
        [0.9933, 0.5000, 0.8808],
        [0.9526, 0.9991, 0.5000],
        [0.8808, 0.9933, 0.8808],
        [0.999

In [189]:
# softmax
torch.softmax(k, dim = 1)

tensor([[1.0651e-01, 1.0651e-01, 7.8699e-01],
        [2.1785e-03, 8.7888e-01, 1.1894e-01],
        [3.2932e-04, 9.8169e-01, 1.7980e-02],
        [9.7556e-01, 6.5733e-03, 1.7868e-02],
        [8.4379e-01, 4.2010e-02, 1.1420e-01],
        [8.9468e-04, 9.8114e-01, 1.7970e-02],
        [1.5876e-02, 8.6681e-01, 1.1731e-01],
        [9.9507e-01, 2.4665e-03, 2.4665e-03],
        [5.7612e-01, 2.1194e-01, 2.1194e-01],
        [2.1194e-01, 2.1194e-01, 5.7612e-01],
        [4.7123e-02, 9.4650e-01, 6.3775e-03],
        [2.6762e-01, 7.2748e-01, 4.9017e-03],
        [9.0031e-02, 2.4473e-01, 6.6524e-01],
        [9.9662e-01, 9.0880e-04, 2.4704e-03],
        [2.4473e-01, 9.0031e-02, 6.6524e-01],
        [2.4561e-03, 6.6764e-03, 9.9087e-01],
        [9.9241e-01, 9.0496e-04, 6.6868e-03],
        [1.0651e-01, 1.0651e-01, 7.8699e-01],
        [6.6920e-03, 9.9319e-01, 1.2257e-04],
        [1.1911e-01, 8.8009e-01, 8.0254e-04],
        [9.9241e-01, 9.0496e-04, 6.6868e-03],
        [1.0651e-01, 1.0651e-01, 7

In [190]:
# relu
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.],
        [0., 8., 4.],
        [7., 2., 3.],
        [8., 5., 6.],
        [2., 9., 5.],
        [0., 4., 2.],
        [7., 1., 1.],
        [5., 4., 4.],
        [1., 1., 2.],
        [4., 7., 2.],
        [5., 6., 1.],
        [4., 5., 6.],
        [9., 2., 3.],
        [1., 0., 2.],
        [1., 2., 7.],
        [9., 2., 4.],
        [6., 6., 8.],
        [4., 9., 0.],
        [7., 9., 2.],
        [7., 0., 2.],
        [4., 4., 6.],
        [2., 1., 0.],
        [5., 1., 0.],
        [0., 2., 2.],
        [3., 7., 1.],
        [5., 0., 2.],
        [3., 7., 0.],
        [2., 5., 2.],
        [8., 0., 2.],
        [5., 3., 6.],
        [7., 8., 1.]])

## Inplace Operations

In [191]:
m = torch.randn(2,3)
n = torch.rand(2,3)

In [192]:
m + n # Consumes an extra of this space

tensor([[ 0.9083, -0.2174,  0.3843],
        [-0.5709, -2.7038,  1.2333]])

In [193]:
m.add_(n) # Doesnot consume Extra Space

tensor([[ 0.9083, -0.2174,  0.3843],
        [-0.5709, -2.7038,  1.2333]])

In [194]:
m

tensor([[ 0.9083, -0.2174,  0.3843],
        [-0.5709, -2.7038,  1.2333]])

In [195]:
m.relu_() ## _ represnt permanant operations

tensor([[0.9083, 0.0000, 0.3843],
        [0.0000, 0.0000, 1.2333]])

In [196]:
m

tensor([[0.9083, 0.0000, 0.3843],
        [0.0000, 0.0000, 1.2333]])

## Copying a Tensor

In [197]:
a = torch.rand(2,3)

In [198]:
a

tensor([[0.2028, 0.9792, 0.4947],
        [0.3617, 0.9687, 0.0359]])

In [199]:
b = a

In [200]:
b

tensor([[0.2028, 0.9792, 0.4947],
        [0.3617, 0.9687, 0.0359]])

In [201]:
a[0][0] = 1

In [202]:
a

tensor([[1.0000, 0.9792, 0.4947],
        [0.3617, 0.9687, 0.0359]])

In [203]:
b # Changes are reflected due to assignment Operators

tensor([[1.0000, 0.9792, 0.4947],
        [0.3617, 0.9687, 0.0359]])

In [204]:
id(a)

137246395820112

In [205]:
id(b)

137246395820112

In [206]:
b = a.clone()

In [207]:
b

tensor([[1.0000, 0.9792, 0.4947],
        [0.3617, 0.9687, 0.0359]])

In [208]:
a[0][0] = 10

In [209]:
b

tensor([[1.0000, 0.9792, 0.4947],
        [0.3617, 0.9687, 0.0359]])

## Tensor Operations on GPU

In [210]:
torch.cuda.is_available()

True

In [211]:
device = torch.device('cuda')

In [212]:
## Creating a New Tensor on GPU
torch.rand((2,3),device = device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [213]:
## Moving an existing tensor on to GPU
a = torch.rand(2,3)

In [214]:
a

tensor([[0.3041, 0.9867, 0.1290],
        [0.6887, 0.1637, 0.0899]])

In [215]:
b = a.to(device)

In [216]:
b

tensor([[0.3041, 0.9867, 0.1290],
        [0.6887, 0.1637, 0.0899]], device='cuda:0')

In [217]:
b + 5

tensor([[5.3041, 5.9867, 5.1290],
        [5.6887, 5.1637, 5.0899]], device='cuda:0')

## Performance Comparison: CPU vs. GPU

In [218]:
import time

# Define matrix dimensions
matrix_size = 10000

# Create two large tensors on CPU
a_cpu = torch.rand(matrix_size, matrix_size)
b_cpu = torch.rand(matrix_size, matrix_size)

# Perform matrix multiplication on CPU and measure time
start_time = time.time()
result_cpu = torch.matmul(a_cpu, b_cpu)
end_time = time.time()
print(f"Time taken on CPU: {end_time - start_time:.4f} seconds")

# Check if GPU is available and move tensors to GPU
if torch.cuda.is_available():
  a_gpu = a_cpu.to(device)
  b_gpu = b_cpu.to(device)

  # Perform matrix multiplication on GPU and measure time
  start_time = time.time()
  result_gpu = torch.matmul(a_gpu, b_gpu)
  end_time = time.time()
  print(f"Time taken on GPU: {end_time - start_time:.4f} seconds")
else:
  print("GPU is not available, so cannot perform GPU comparison.")

Time taken on CPU: 19.8194 seconds
Time taken on GPU: 0.0005 seconds


## Reshaping Tensors

In [219]:
a = torch.ones(1,4)

In [220]:
a

tensor([[1., 1., 1., 1.]])

In [221]:
# reshape
a.reshape(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [222]:
a.flatten()

tensor([1., 1., 1., 1.])

In [227]:
b = torch.randn(2,3,4)

In [228]:
b

tensor([[[-0.5455, -1.0230,  0.2549, -0.0644],
         [ 0.0514,  1.5381, -1.2833, -1.1880],
         [-0.6623, -0.5096,  0.8157, -1.5613]],

        [[-0.0661, -0.3935, -0.9158, -0.2603],
         [-0.9768, -0.8462,  1.9873,  0.6698],
         [ 1.4738,  0.9124, -0.7304,  0.7511]]])

In [229]:

b.permute(2,0,1)

tensor([[[-0.5455,  0.0514, -0.6623],
         [-0.0661, -0.9768,  1.4738]],

        [[-1.0230,  1.5381, -0.5096],
         [-0.3935, -0.8462,  0.9124]],

        [[ 0.2549, -1.2833,  0.8157],
         [-0.9158,  1.9873, -0.7304]],

        [[-0.0644, -1.1880, -1.5613],
         [-0.2603,  0.6698,  0.7511]]])

In [230]:
# Squeeze: Remove dimensions of size 1
c = torch.randn(1, 3, 1, 4)
print(f"Original tensor c: {c.shape}")

squeezed_c = c.squeeze()
print(f"Squeezed tensor c: {squeezed_c.shape}")

Original tensor c: torch.Size([1, 3, 1, 4])
Squeezed tensor c: torch.Size([3, 4])


In [231]:
# Unsqueeze: Add a dimension of size 1 at a specified position
d = torch.randn(3, 4)
print(f"Original tensor d: {d.shape}")

unsqueeze_d = d.unsqueeze(0) # Add a new dimension at index 0
print(f"Unsqueeze tensor d (dim 0): {unsqueeze_d.shape}")

unsqueeze_d_2 = d.unsqueeze(1) # Add a new dimension at index 1
print(f"Unsqueeze tensor d (dim 1): {unsqueeze_d_2.shape}")

Original tensor d: torch.Size([3, 4])
Unsqueeze tensor d (dim 0): torch.Size([1, 3, 4])
Unsqueeze tensor d (dim 1): torch.Size([3, 1, 4])


## Numpy and Pytorch

In [232]:
import numpy as np

In [233]:
a = torch.tensor([1,2,3])

In [234]:
b = a.numpy()

In [235]:
b

array([1, 2, 3])

In [236]:
type(b)

numpy.ndarray

In [237]:
c = np.array([1,2,3])

In [239]:
d = torch.from_numpy(c)

In [240]:
type(d)

torch.Tensor